### ISSUE TITLE
Failed to run "fab cluster render"

### ISSUE THREAD

**Issue by oomichi** [nec-openstack/remora#10]
$ fab cluster render
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/fabric/main.py", line 672, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/fabric/main.py", line 173, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/ubuntu/remora/fabfile.py", line 18, in <module>
    from remora.fab import clean        # noqa
  File "/home/ubuntu/remora/remora/fab/clean/__init__.py", line 25, in <module>
    from remora.fab.clean import kubernetes
  File "/home/ubuntu/remora/remora/fab/clean/kubernetes.py", line 20, in <module>
    from remora.fab.clean import utils
  File "/home/ubuntu/remora/remora/fab/clean/utils.py", line 17, in <module>
    from remora.fab import helpers
  File "/home/ubuntu/remora/remora/fab/helpers.py", line 140
    def run_script(script_name, *options, local_env=[]):
                                                  ^
SyntaxError: invalid syntax

**Comment by yuanying** [comment]
Sorry, this scripts only support Python 3.5 or later.

**Comment by oomichi** [comment]
I cannot find such NOTE and it would be better to check the version if so.

**Comment by yuanying** [comment]
I'm just writing to add such NOTE now! lol

**Comment by oomichi** [comment]
or support py27!

**Comment by oomichi** [comment]
"fab cluster render" is still failed.

[..]
e is 65537 (0x10001)
Signature ok
subject=/O=system:masters/CN=kubernetes-admin
Getting CA Private Key
Generating RSA private key, 4096 bit long modulus
..................................++
..........................................................................................................................................................................++
e is 65537 (0x10001)
Signature ok
subject=/O=system:masters/CN=kube-kubelet-client
Getting CA Private Key
/home/ubuntu/remora/remora/scripts/certs/kubernetes/render-server-cert.sh: line 14: KUBE_PUBLIC_SERVICE_IP: unbound variable

Fatal error: local() encountered an error (return code 1) while executing 'source /tmp/tmp_gm3bgv5/default-env.sh && bash /home/ubuntu/remora/remora/scripts/certs/kubernetes/render.sh '

Aborting.

**Comment by yuanying** [comment]
You missed to add following required parameter in your config file.

```yaml
kubernetes:
  # Public kubernetes service address
  public_service_ip: 192.168.1.101
```

**Comment by oomichi** [comment]
Thanks, that was my misconfiguration.
