### ISSUE TITLE
ubuntu 16.04 doesn't provide docker-engine 1.12 at the default

### ISSUE THREAD

**Issue by oomichi** [nec-openstack/remora#9]
Now the latest docker-engine is 1.11.2-0~xenial at ubuntu 16.04.
So do we recommend to install docker-engine manually without a package ?

**Comment by yuanying** [comment]
You can build Docker 1.12 pre installed image using diskimage-builder which is loved by OpenStackers (you seem openstacker, right?)

Procedure is described below.

* https://github.com/yuanying/k8s-env/blob/master/elements/docker-install/README.md

But I guess Docker 1.11 is enough to deploy kubernetes.

**Comment by oomichi** [comment]
Then I am not OpenStacker because I don't like to hear the word diskimage-builder :)
Thanks for your info, anyways.
